// 学校列表配置（可随时增删）
export const schoolOptions = [
  { text: '🌍 赣饶·广丰（全区）', value: null },
  { text: '广丰中学', value: '广丰中学' },
  { text: '广丰一中', value: '广丰一中' },
  { text: '贞白中学', value: '贞白中学' },
  { text: '洋口中学', value: '洋口中学' },
  { text: '五都中学', value: '五都中学' },
  { text: '新实中学', value: '新实中学' },
  { text: '恒立中学', value: '恒立中学' },
  { text: '金桥中学', value: '金桥中学' },
  { text: '康桥中学', value: '康桥中学' },
  { text: '丰溪中学', value: '丰溪中学' },
  { text: '南屏中学', value: '南屏中学' },
  { text: '横山中学', value: '横山中学' },
  { text: '芦林中学', value: '芦林中学' },
  { text: '实验中学', value: '实验中学' },
  { text: '永丰中学', value: '永丰中学' },
  { text: '清江中学', value: '清江中学' },
  { text: '凤凰技校', value: '凤凰技校' },
  { text: '博雅中学', value: '博雅中学' },
  { text: '叔叶中学', value: '叔叶中学' },
  { text: '大石中学', value: '大石中学' },
  { text: '南山中学', value: '南山中学' },
  { text: '职高中学', value: '职高中学' },
  { text: '上饶卫校', value: '上饶卫校' },
  { text: '下溪中学', value: '下溪中学' },
  { text: '湖丰中学', value: '湖丰中学' },
  { text: '塘xi中学', value: '塘xi中学' },
  { text: '铜钹山中学', value: '铜钹山中学' },
  { text: '大千艺术', value: '大千艺术' },
  { text: '大南中学', value: '大南中学' },
  { text: '桐畈中学', value: '桐畈中学' },
  // 可继续添加...
]